language: java
jdk:
  - openjdk11
# git strips the wrapper jar file so we have to force its download during the build
install:
  - mvn -N io.takari:maven:wrapper
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  sonarcloud:
    organization: "Bill Konstantinou"
    token:
      secure: $SONAR_CLOUD

scripts:
  - ./mvnw clean install -B
  - ./mvnw clean verify sonar:sonar -Pcoverage
#  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar