language: java
jdk:
  - openjdk11
# git strips the wrapper jar file so we have to force its download during the build

addons:
  sonarcloud:
    organization: "Bill Konstantinou"
    token:
      secure: $SONAR_CLOUD

scripts:
  - ./mvnw clean install -B
  - ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar